version: '3'
services:
  db8:
    image: mysql:8.0
    container_name: db8
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes:
      - ./dbdata:/var/lib/mysql
    ports:
    - '3305:3306' # For accessing db from outside of container. Do not use on production
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  wordpress:
    depends_on:
      - db8
    image: wordpress:5.7-fpm # Without apache installed
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db8:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - ./wp:/var/www/html # wp engine
      - ./themes:/var/www/html/wp-content/themes
    networks:
      - app-network

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.15.12
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./wp:/var/www/html # wp engine
      - ./themes:/var/www/html/wp-content/themes
      - ./nginx-conf/staging:/etc/nginx/conf.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

